### ISSUE TITLE
Decide on testing framework and add tests for the login API

### ISSUE THREAD

**Issue by kevinlul** [ccmbioinfo/ST2020#38]
Flask testing docs: https://flask.palletsprojects.com/en/1.1.x/testing/
Possible Frameworks:
- pytest: https://docs.pytest.org/en/latest/
- hypothesis (property-based testing; generates test cases): https://hypothesis.readthedocs.io/en/latest/index.html

**Comment by frewmack** [comment]
Found another framework that complements pytest:
- coverage (reports the est. total % of code covered by test cases): https://coverage.readthedocs.io/en/coverage-5.3/
