### ISSUE TITLE
Add table NGSType

### ISSUE THREAD

**Issue by kevinlul** [ccmbioinfo/ST2020#44]
Columns:
- enum type (genomic, rnaseq, exonic, RNA, single cell?)
- Foreign key DatasetType
- Primary key across both

Change PipelineDatasets to use NGSType (feel free to rename the table)

Create a list of all our supported pipelines and what datasets they support as part of the scope of this issue.

**Comment by helrick** [comment]
Spoke with Magda about this and she suggested using MetaDataType to future-proof the field in case of future studies using non-genomic data (metabolomics, methylation, etc.)
