### ISSUE TITLE
Editing data in tables: try cell edits vs row edits

### ISSUE THREAD

**Issue by kevinlul** [ccmbioinfo/ST2020#79]

**Comment by frewmack** [comment]
![image](https://user-images.githubusercontent.com/11793063/96165431-9af7cf80-0eea-11eb-85db-f98ce2a7406a.png)
So material-table has its own component for editing individual cells. The only problem is that you can't click on it if that cell is empty. I'm not sure if there's a way to override this component, but I will look into it.
